collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5947303
color:
  saturation: 0.5049002
  brandStrength: 0.7995132
  lightness: 0.09939695
  brandColors:
    - '#C8F3FF'
    - '#23282C'
    - '#675446'
    - '#B88A7A'
    - '#E6B89E'
  rhythmicContrast: 0.9643877
layout_spectrum: 0.7401434
name: Improv Camp
