collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5687103786040097
color:
  saturation: 0.06914935633540154
  brandStrength: 0.08561918931081891
  lightness: 0.74943459010683
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.7566317138262093
layout_spectrum: 0.6989945820532739
name: Improv Camp
